### ISSUE TITLE
Updating multiple menu items during one event seems to cause a panic

### ISSUE THREAD

**Issue by dscottboggs** [amrbashir/menu-rs#40]
I've made this minimal example based on [the tao example](https://github.com/tauri-apps/tray-icon/blob/dev/examples/tao.rs) in the tray-icon crate:

```rust
// Copyright 2022-2022 Tauri Programme within The Commons Conservancy
// SPDX-License-Identifier: Apache-2.0
// SPDX-License-Identifier: MIT

#![allow(unused)]

use tao::event_loop::{ControlFlow, EventLoopBuilder};
use tray_icon::{
    icon::Icon,
    menu::{
        AboutMetadata, CheckMenuItem, Menu, MenuEvent, MenuItem, PredefinedMenuItem,
        Submenu,
    },
    TrayEvent, TrayIconBuilder,
};

fn main() {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/examples/icon.png");
    let icon = load_icon(std::path::Path::new(path));

    let event_loop = EventLoopBuilder::new().build();

    let tray_menu = Menu::new();

    let quit_i = MenuItem::new("Quit", true, None);
    let submenu = Submenu::new("Sub-menu", true);
    let one = CheckMenuItem::new("Option One", true, true, None);
    let two = CheckMenuItem::new("Option Two", true, false, None);
    submenu.append_items(&[&one, &two]);
    tray_menu.append_items(&[
        &PredefinedMenuItem::about(
            None,
            Some(AboutMetadata {
                name: Some("tao".to_string()),
                copyright: Some("Copyright tao".to_string()),
                ..Default::default()
            }),
        ),
        &submenu,
        &PredefinedMenuItem::separator(),
        &quit_i,
    ]);

    let mut tray_icon = Some(
        TrayIconBuilder::new()
            .with_menu(Box::new(tray_menu))
            .with_tooltip("tao - awesome windowing lib")
            .with_icon(icon)
            .build()
            .unwrap(),
    );

    let menu_channel = MenuEvent::receiver();
    let tray_channel = TrayEvent::receiver();

    event_loop.run(move |_event, _target, control_flow| {
        *control_flow = ControlFlow::Poll;

        if let Ok(event) = menu_channel.try_recv() {
            if event.id == quit_i.id() {
                tray_icon.take();
                *control_flow = ControlFlow::Exit;
            } else if event.id == one.id() || event.id == two.id() {
                // swap one and two
                let [one_set, two_set] = [one.is_checked(), two.is_checked()];
                one.set_checked(!one_set);
                // panic happens here:
                two.set_checked(!two_set);
            }
            println!("{:?}", event);
        }

        if let Ok(event) = tray_channel.try_recv() {
            println!("{:?}", event);
        }
    })
}

fn load_icon(path: &std::path::Path) -> tray_icon::icon::Icon {
    let (icon_rgba, icon_width, icon_height) = {
        let image = image::open(path)
            .expect("Failed to open icon path")
            .into_rgba8();
        let (width, height) = image.dimensions();
        let rgba = image.into_raw();
        (rgba, width, height)
    };
    tray_icon::icon::Icon::from_rgba(icon_rgba, icon_width, icon_height)
        .expect("Failed to open icon")
}
```

When I run this code, then click either submenu item, the program panics with this message:

```
thread 'main' panicked at 'already mutably borrowed: BorrowError', /home/scott/.cargo/registry/src/github.com-1ecc6299db9ec823/muda-0.4.0/src/platform_impl/gtk/mod.rs:1046:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3020239de947ec52677e9b4e853a6a9fc073d1f9/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/3020239de947ec52677e9b4e853a6a9fc073d1f9/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/3020239de947ec52677e9b4e853a6a9fc073d1f9/library/core/src/result.rs:1790:5
   3: core::result::Result<T,E>::expect
             at /rustc/3020239de947ec52677e9b4e853a6a9fc073d1f9/library/core/src/result.rs:1069:23
   4: core::cell::RefCell<T>::borrow
             at /rustc/3020239de947ec52677e9b4e853a6a9fc073d1f9/library/core/src/cell.rs:866:9
   5: muda::platform_impl::platform::CheckMenuItem::make_gtk_menu_item::{{closure}}
             at /home/scott/.cargo/registry/src/github.com-1ecc6299db9ec823/muda-0.4.0/src/platform_impl/gtk/mod.rs:1045:35
   6: <O as gtk::auto::check_menu_item::CheckMenuItemExt>::connect_toggled::toggled_trampoline
             at /home/scott/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.16.2/src/auto/check_menu_item.rs:614:13
   7: g_closure_invoke
   8: <unknown>
   9: g_signal_emit_valist
  10: g_signal_emit
  11: <unknown>
  12: g_closure_invoke
  13: <unknown>
  14: g_signal_emit_valist
  15: g_signal_emit
  16: <O as gtk::auto::check_menu_item::CheckMenuItemExt>::set_active
             at /home/scott/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.16.2/src/auto/check_menu_item.rs:577:13
  17: muda::platform_impl::platform::MenuChild::set_checked
             at /home/scott/.cargo/registry/src/github.com-1ecc6299db9ec823/muda-0.4.0/src/platform_impl/gtk/mod.rs:160:17
  18: muda::platform_impl::platform::CheckMenuItem::set_checked
             at /home/scott/.cargo/registry/src/github.com-1ecc6299db9ec823/muda-0.4.0/src/platform_impl/gtk/mod.rs:1113:9
  19: muda::check_menu_item::CheckMenuItem::set_checked
             at /home/scott/.cargo/registry/src/github.com-1ecc6299db9ec823/muda-0.4.0/src/check_menu_item.rs:82:9
  20: tray2::main::{{closure}}
             at ./examples/tray2.rs:67:17
  21: tao::platform_impl::platform::event_loop::EventLoop<T>::run_return::{{closure}}
             at /home/scott/.cargo/git/checkouts/tao-b2c91e21b396bd53/bfd9de4/src/platform_impl/linux/event_loop.rs:968:17
  22: glib::main_context::<impl glib::auto::main_context::MainContext>::with_thread_default
             at /home/scott/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.16.7/src/main_context.rs:156:12
  23: tao::platform_impl::platform::event_loop::EventLoop<T>::run_return
             at /home/scott/.cargo/git/checkouts/tao-b2c91e21b396bd53/bfd9de4/src/platform_impl/linux/event_loop.rs:871:5
  24: tao::platform_impl::platform::event_loop::EventLoop<T>::run
             at /home/scott/.cargo/git/checkouts/tao-b2c91e21b396bd53/bfd9de4/src/platform_impl/linux/event_loop.rs:825:21
  25: tao::event_loop::EventLoop<T>::run
             at /home/scott/.cargo/git/checkouts/tao-b2c91e21b396bd53/bfd9de4/src/event_loop.rs:216:5
  26: tray2::main
             at ./examples/tray2.rs:57:5
  27: core::ops::function::FnOnce::call_once
             at /rustc/3020239de947ec52677e9b4e853a6a9fc073d1f9/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by amrbashir** [comment]
could you check if #48 fixes the issue for you? thanks

**Comment by dscottboggs** [comment]
No, sorry, same crash.

**Comment by amrbashir** [comment]
May I ask how did you test the PR? I have used your example and it works without a problem.

**Comment by dscottboggs** [comment]
I'm sorry, I've just realized it makes no sense for me to still be getting the "same crash". I should've looked closer. I figured it out what I did wrong, the patch works. Thanks.
