### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'GTK may only be used from the main thread.'

### ISSUE THREAD

**Issue by karfield** [amrbashir/menu-rs#80]
try to use muda in my tauri project(following code, tauri version 2.0.0-alpha.10), but 'GTK may only be used from the main thread' panicked!

```rust

#[tokio::main]
async fn main() {
    tauri::Builder::new()
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(tauri::generate_handler![
            open_menu,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri");
}

#[tauri::command]
pub async fn open_menu(
    x: f64,
    y: f64,
    window: Window,
) -> Result<(), String> {
    let menu = Menu::new();
    // init menu stuff...

   #[cfg(target_os = "windows")]
   menu.show_context_menu_for_hwnd(window.hwnd() as isize, x, y);
   #[cfg(target_os = "linux")]
   menu.show_context_menu_for_gtk_window(&gtk_window, x, y);
   #[cfg(target_os = "macos")]
   menu.show_context_menu_for_nsview(nsview, x, y);

    Ok(())
}

```

panics:

```
thread 'tokio-runtime-worker' panicked at 'GTK may only be used from the main thread.', /home/karfield/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtk-0.16.2/src/auto/menu.rs:40:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: gtk::auto::menu::Menu::new
             at /home/karfield/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtk-0.16.2/src/auto/menu.rs:40:9
   3: muda::platform_impl::platform::Menu::gtk_context_menu
             at /home/karfield/.cargo/registry/src/index.crates.io-6f17d22bba15001f/muda-0.7.0/src/platform_impl/gtk/mod.rs:334:40
   4: muda::platform_impl::platform::Menu::show_context_menu_for_gtk_window
             at /home/karfield/.cargo/registry/src/index.crates.io-6f17d22bba15001f/muda-0.7.0/src/platform_impl/gtk/mod.rs:326:27
   5: <muda::menu::Menu as muda::ContextMenu>::show_context_menu_for_gtk_window
             at /home/karfield/.cargo/registry/src/index.crates.io-6f17d22bba15001f/muda-0.7.0/src/menu.rs:302:9
   6: javue::app::context_menu::show_context_menu
             at ./core/src/app/context_menu.rs:51:5
```

 SO HOW TO MAKE menu.show_context_menu_ running in main thread ? 'wry example' shows it possible to  create 
 EventLoopBuilder and single window in main(), but HOW to merge with tauri code?

**Comment by FabianLars** [comment]
try a non-async tauri command. They will be executed on the main thread. No promises that that will work but it will get you closer :)

**Comment by karfield** [comment]
This can work! but also needs to create a tokio runtime manually :<

**Comment by FabianLars** [comment]
You can access Tauri's running tokio runtime via spawn/block_on from https://docs.rs/tauri/latest/tauri/async_runtime/index.html - alternative you can also try making the command async again, and then use an AppHandle or Window to use https://docs.rs/tauri/latest/tauri/struct.AppHandle.html#method.run_on_main_thread
